{% set version = "4.13.2" %}

package:
  name: libitk
  version: "{{version}}"

source:
  url: https://github.com/InsightSoftwareConsortium/ITK/archive/v{{version}}.tar.gz
  sha256: 98c2fd826e1987d797521d83031fcaa328135daf6524f7823363d66ab288c545

build:
    number: 4

requirements:
  build:
    - cmake    >=3.3
    - ninja
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - expat                     # [not win]
    - hdf5                      # [not win]
    - jpeg
    - libtiff
    - libpng
    - zlib                      # [not win]
  run:
    - expat                     # [not win]
    - hdf5                      # [not win]
    - jpeg
    - libtiff
    - libpng
    - zlib                      # [not win]

test:
  requires:
    - cmake
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
  files:
    - example
    - ITK-JPEG.jpg
  commands:
    - test -d $PREFIX/include/ITK*                        # [not win]
    - if not exist %LIBRARY_INC%\\ITK* exit 1             # [win]
    - itkTestDriver -- echo "Runtime ITK OK"
    - itkTestDriver --no-process --compare-MD5 ITK-JPEG.jpg 959e1682d19026fc62cfbdc140df31da
    - cmake -D "CMAKE_SYSTEM_PREFIX_PATH:FILEPATH=${PREFIX}" ./example  # [not win]
    - cmake --build . --config Release                                  # [not win]

about:
  home: http://www.itk.org
  license: Apache 2.0
  license_file:
    - LICENSE
    - NOTICE
  summary: Runtime libraries and header files for the Insight Toolkit for segmentation and registration.

extra:
    recipe-maintainers:
      - blowekamp
      - bluescarni
